spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/tms-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

application:
  name: task-management-system
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${EXPIRATION}

---

spring:

  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/tms-test-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://tms-postgres:5432/tms-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml