### Создание комментария
POST http://localhost:8080/api/v1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqbzIyaHJuLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTcyMjgwNDA2MSwiZXhwIjoxNzIyODkwNDYxfQ.ady1xb1PU3EiTMAN2ifTU9wZ6-B7KP9B1oJ-0dFHrqY

{
  "content": "New comment",
  "taskId": 1
}

### Получить комментарии у задачи 1
GET http://localhost:8080/api/v1/comments?taskId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqbzIyaHJuLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTcyMjgwNDA2MSwiZXhwIjoxNzIyODkwNDYxfQ.ady1xb1PU3EiTMAN2ifTU9wZ6-B7KP9B1oJ-0dFHrqY
